### ISSUE TITLE
Fix formatting issue in data.js

### ISSUE THREAD

**Issue by LeeVaughn** [LeeVaughn/treehouse-hacktoberfesters#15]
The data for Agata Z in the `data.js` file includes single quotes around the property names. These need to be removed so that the formatting matches what is shown in the data example of the README.

If you would like to work on this issue please respond to this post and I will assign it to you.

Thanks!

**Comment by JelenaMF** [comment]
I can. If no one else has already.

**Comment by LeeVaughn** [comment]
Hey @Jaaylena! All yours, go for it! 👍
